### ISSUE TITLE
n8n error when https on error on logs permission denied  '/ssl/privkey.pem'

### ISSUE THREAD

**Issue by shirou93** [Rbillon59/home-assistant-addons#7]
hi,
this is my log:
```
Initializing n8n process
 ›   Error: There was an error: EACCES: permission denied, open 
 ›   '/ssl/privkey.pem'
```

**Comment by Rbillon59** [comment]
Hi @shirou93 

Your logs seems not related to the add-on itself.

Have you generated key and certificate beforehand ? 

Can you give the permission over these files and on the folder ?

Thanks you !

**Comment by shirou93** [comment]
I have cert generated with duckdns addon in SSL folder.

**Comment by Rbillon59** [comment]
Hi again,

Just having some tests on my own instance, 

![image](https://user-images.githubusercontent.com/17565349/150700203-b93ff65e-07b8-4a21-8210-3ccb3233dc65.png)

![image](https://user-images.githubusercontent.com/17565349/150700232-f45b0992-040c-4575-a243-78d6a80f1211.png)

![image](https://user-images.githubusercontent.com/17565349/150700255-dce253c9-567e-4e6d-a3c8-9d38b79822b4.png)

![image](https://user-images.githubusercontent.com/17565349/150700272-6225a214-bd24-471f-b8df-3ab97258905c.png)

If you can check your files and folders permissions because, over there, all is working fine. Would you give me more insight so I can help you getting rid of this error ?

**Comment by shirou93** [comment]
key created by duckdns addon:

![image](https://user-images.githubusercontent.com/59237288/150701378-537adadf-7dbe-4751-9ed8-11273277e92d.png)

**Comment by Rbillon59** [comment]
I didn't dig in other addons configuration, but I guess they are not changing the runtime user so it's root. 

Here, your logs is saying that only the root user can read and write the pem files. Unfortunately the user that run N8N in the addon is `node` thus, this user is unable to read the key files.

You could just adding the read capability for other users by running : chmod 644 fullchain.pem privkey.pem

**Comment by shirou93** [comment]
Thanks for check
